language: java
dist: trusty
install: skip
sudo: required
services:
  - docker

jobs:
  include:

    - stage: build
      jdk: openjdk8
      env: LIBRARY_ENRICHMENT
      script:
        - cd library-enrichment
        - ./gradlew build
    - stage: build
      jdk: openjdk11
      env: LIBRARY_ENRICHMENT
      script:
        - cd library-enrichment
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: LIBRARY_SERVICE
      script:
        - cd library-service
        - ./gradlew build
    - stage: build
      jdk: openjdk11
      env: LIBRARY_SERVICE
      script:
        - cd library-service
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: LIBRARY_INTEGRATION_SLACK
      script:
        - cd library-integration-slack
        - ./gradlew build
    - stage: build
      jdk: openjdk11
      env: LIBRARY_INTEGRATION_SLACK
      script:
        - cd library-integration-slack
        - ./gradlew build
