version: 2

jobs:
  ci-library-enrichment:
    working_directory: ~/work
    machine: true
    steps:
      - checkout
      - run: cd library-enrichment && ./gradlew build
      - store_test_results:
          path: library-enrichment/build/test-results
  ci-library-integration-slack:
    working_directory: ~/work
    machine: true
    steps:
      - checkout
      - run: cd library-integration-slack && ./gradlew build
      - store_test_results:
          path: library-integration-slack/build/test-results
  ci-library-service:
    working_directory: ~/work
    machine: true
    steps:
      - checkout
      - run: cd library-service && ./gradlew build
      - store_test_results:
          path: library-service/build/test-results

workflows:
  version: 2
  ci-build:
    jobs:
    - ci-library-enrichment
    - ci-library-integration-slack
    - ci-library-service
